name: Lint PR
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed.
          # Default is: https://github.com/commitizen/conventional-commit-types
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
            meta
          # Configure that a scope must be always lowercase.
          subjectPattern: ^(?![A-Z]).+$
          # If the PR contains a breaking change, the title must contain a ! 
          # or the footer must contain BREAKING CHANGE:
          requireScope: false
